//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBEAccounts.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUBEAccounts.Message.SL", typeof(SL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundMaster_AcYearList.
        /// </summary>
        public static string FundMaster_AcYearList {
            get {
                return ResourceManager.GetString("FundMaster_AcYearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundMaster_List.
        /// </summary>
        public static string FundMaster_List {
            get {
                return ResourceManager.GetString("FundMaster_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundMaster_Save.
        /// </summary>
        public static string FundMaster_Save {
            get {
                return ResourceManager.GetString("FundMaster_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FundMaster_YearEnd.
        /// </summary>
        public static string FundMaster_YearEnd {
            get {
                return ResourceManager.GetString("FundMaster_YearEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger_Delete.
        /// </summary>
        public static string Ledger_Delete {
            get {
                return ResourceManager.GetString("Ledger_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger_Save.
        /// </summary>
        public static string Ledger_Save {
            get {
                return ResourceManager.GetString("Ledger_Save", resourceCulture);
            }
        }
    }
}
